/**
 * storage/index.ts
 *
 * Assembles all domain-specific storage functions into a single `storage` singleton
 * that matches the original DatabaseStorage interface exactly.
 *
 * All route files and service files import from `./storage` which re-exports this.
 */

export * from "./users";
export * from "./practices";
export * from "./patients";
export * from "./claims";
export * from "./payments";
export * from "./clinical";
export * from "./appointments";
export * from "./insurance";
export * from "./analytics";
export * from "./audit";

// Re-export all domain functions as methods on a storage object for backwards compatibility
import * as userFns from "./users";
import * as practiceFns from "./practices";
import * as patientFns from "./patients";
import * as claimFns from "./claims";
import * as paymentFns from "./payments";
import * as clinicalFns from "./clinical";
import * as appointmentFns from "./appointments";
import * as insuranceFns from "./insurance";
import * as analyticsFns from "./analytics";
import * as auditFns from "./audit";

export const storage = {
  // ==================== USERS ====================
  getUser: userFns.getUser,
  upsertUser: userFns.upsertUser,
  getAllUsers: userFns.getAllUsers,
  updateUserRole: userFns.updateUserRole,
  getUserByEmail: userFns.getUserByEmail,
  createUserWithPassword: userFns.createUserWithPassword,
  updatePasswordHash: userFns.updatePasswordHash,
  setPasswordResetToken: userFns.setPasswordResetToken,
  clearPasswordResetToken: userFns.clearPasswordResetToken,
  getUserByPasswordResetToken: userFns.getUserByPasswordResetToken,
  incrementFailedLoginAttempts: userFns.incrementFailedLoginAttempts,
  resetFailedLoginAttempts: userFns.resetFailedLoginAttempts,
  setLockout: userFns.setLockout,
  setEmailVerificationToken: userFns.setEmailVerificationToken,
  getUserByEmailVerificationToken: userFns.getUserByEmailVerificationToken,
  verifyEmail: userFns.verifyEmail,
  updateLastLoginAt: userFns.updateLastLoginAt,
  clearAllUserSessions: userFns.clearAllUserSessions,
  getTherapistsByPractice: userFns.getTherapistsByPractice,
  updateUser: userFns.updateUser,
  updateUserMfa: userFns.updateUserMfa,
  getSupervisees: userFns.getSupervisees,
  updateUserSupervision: userFns.updateUserSupervision,
  getAdminsByPractice: userFns.getAdminsByPractice,
  getUserBySsoExternalId: userFns.getUserBySsoExternalId,
  createInvite: userFns.createInvite,
  getInvitesByPractice: userFns.getInvitesByPractice,
  getInviteByToken: userFns.getInviteByToken,
  getInviteByEmail: userFns.getInviteByEmail,
  updateInviteStatus: userFns.updateInviteStatus,

  // ==================== PRACTICES ====================
  createPractice: practiceFns.createPractice,
  getPractice: practiceFns.getPractice,
  getAllPracticeIds: practiceFns.getAllPracticeIds,
  updatePractice: practiceFns.updatePractice,
  getPayerCredentials: practiceFns.getPayerCredentials,
  upsertPayerCredentials: practiceFns.upsertPayerCredentials,
  getAllPayerCredentials: practiceFns.getAllPayerCredentials,
  updatePayerHealthStatus: practiceFns.updatePayerHealthStatus,
  getPayerCredentialForPractice: practiceFns.getPayerCredentialForPractice,
  updatePayerCredential: practiceFns.updatePayerCredential,
  createPayerCredential: practiceFns.createPayerCredential,
  getAllPayerCredentialsList: practiceFns.getAllPayerCredentialsList,
  getPayerIntegrationByCode: practiceFns.getPayerIntegrationByCode,
  getPayerIntegrations: practiceFns.getPayerIntegrations,
  updatePayerIntegration: practiceFns.updatePayerIntegration,
  getSsoConfigByPractice: practiceFns.getSsoConfigByPractice,
  getSsoConfigByEmailDomain: practiceFns.getSsoConfigByEmailDomain,
  upsertSsoConfig: practiceFns.upsertSsoConfig,
  updateSsoConfig: practiceFns.updateSsoConfig,

  // ==================== PATIENTS ====================
  createPatient: patientFns.createPatient,
  getPatients: patientFns.getPatients,
  getPatient: patientFns.getPatient,
  getPatientByEmail: patientFns.getPatientByEmail,
  updatePatient: patientFns.updatePatient,
  softDeletePatient: patientFns.softDeletePatient,
  getAllPatients: patientFns.getAllPatients,
  searchPatients: patientFns.searchPatients,
  countAllPatients: patientFns.countAllPatients,
  getPatientsByIds: patientFns.getPatientsByIds,
  hardDeletePatient: patientFns.hardDeletePatient,
  getExpiredSoftDeletedPatients: patientFns.getExpiredSoftDeletedPatients,
  updatePatientIntakeData: patientFns.updatePatientIntakeData,
  completePatientIntake: patientFns.completePatientIntake,
  updatePatientStripeCustomerId: patientFns.updatePatientStripeCustomerId,
  createTreatmentSession: patientFns.createTreatmentSession,
  getTreatmentSessions: patientFns.getTreatmentSessions,
  getTreatmentSession: patientFns.getTreatmentSession,
  getAllSessions: patientFns.getAllSessions,
  createSession: patientFns.createSession,
  createPatientConsent: patientFns.createPatientConsent,
  getPatientConsents: patientFns.getPatientConsents,
  getPatientConsentsByType: patientFns.getPatientConsentsByType,
  getActiveConsent: patientFns.getActiveConsent,
  revokeConsent: patientFns.revokeConsent,
  getConsentsByPractice: patientFns.getConsentsByPractice,
  hasActiveConsent: patientFns.hasActiveConsent,
  hasRequiredTreatmentConsents: patientFns.hasRequiredTreatmentConsents,
  batchGetConsentStatus: patientFns.batchGetConsentStatus,
  createPatientProgressNote: patientFns.createPatientProgressNote,
  getPatientProgressNotes: patientFns.getPatientProgressNotes,
  getPatientProgressNote: patientFns.getPatientProgressNote,
  getSharedPatientProgressNotes: patientFns.getSharedPatientProgressNotes,
  sharePatientProgressNote: patientFns.sharePatientProgressNote,
  unsharePatientProgressNote: patientFns.unsharePatientProgressNote,
  createPatientStatement: patientFns.createPatientStatement,
  generateStatementNumber: patientFns.generateStatementNumber,
  getPatientStatements: patientFns.getPatientStatements,
  getPatientStatement: patientFns.getPatientStatement,
  updatePatientStatement: patientFns.updatePatientStatement,
  markStatementSent: patientFns.markStatementSent,
  markStatementPaid: patientFns.markStatementPaid,
  getPracticeStatements: patientFns.getPracticeStatements,
  createPlanDocument: patientFns.createPlanDocument,
  getPlanDocuments: patientFns.getPlanDocuments,
  getPlanDocument: patientFns.getPlanDocument,
  updatePlanDocument: patientFns.updatePlanDocument,
  deletePlanDocument: patientFns.deletePlanDocument,
  createPlanBenefits: patientFns.createPlanBenefits,
  getPatientPlanBenefits: patientFns.getPatientPlanBenefits,
  getAllPatientPlanBenefits: patientFns.getAllPatientPlanBenefits,
  updatePlanBenefits: patientFns.updatePlanBenefits,
  deactivatePlanBenefits: patientFns.deactivatePlanBenefits,
  verifyPlanBenefits: patientFns.verifyPlanBenefits,
  getPatientArAging: patientFns.getPatientArAging,

  // ==================== CLAIMS ====================
  createClaim: claimFns.createClaim,
  getClaims: claimFns.getClaims,
  countClaims: claimFns.countClaims,
  getClaim: claimFns.getClaim,
  getClaimsByIds: claimFns.getClaimsByIds,
  updateClaim: claimFns.updateClaim,
  createClaimLineItem: claimFns.createClaimLineItem,
  getClaimLineItems: claimFns.getClaimLineItems,
  deleteClaimLineItems: claimFns.deleteClaimLineItems,
  createExpense: claimFns.createExpense,
  getExpenses: claimFns.getExpenses,
  getExpense: claimFns.getExpense,
  updateExpense: claimFns.updateExpense,
  createPayment: claimFns.createPayment,
  getPayments: claimFns.getPayments,
  getCptCodes: claimFns.getCptCodes,
  getAllCptCodes: claimFns.getAllCptCodes,
  getIcd10Codes: claimFns.getIcd10Codes,
  getInsurances: claimFns.getInsurances,
  getInsurance: claimFns.getInsurance,
  getCptCodeMappings: claimFns.getCptCodeMappings,
  createCptCodeMapping: claimFns.createCptCodeMapping,
  createReimbursementOptimization: claimFns.createReimbursementOptimization,
  getClaimAppeals: claimFns.getClaimAppeals,
  updateAppealStatus: claimFns.updateAppealStatus,
  getDeniedClaimsByDateRange: claimFns.getDeniedClaimsByDateRange,
  getDeniedClaimsWithDetails: claimFns.getDeniedClaimsWithDetails,
  getInsuranceRates: claimFns.getInsuranceRates,
  getInsuranceRateByCode: claimFns.getInsuranceRateByCode,
  createInsuranceRate: claimFns.createInsuranceRate,
  updateInsuranceRate: claimFns.updateInsuranceRate,
  deleteInsuranceRate: claimFns.deleteInsuranceRate,
  upsertInsuranceRate: claimFns.upsertInsuranceRate,
  getUniqueInsuranceProviders: claimFns.getUniqueInsuranceProviders,
  getRatesRankedByReimbursement: claimFns.getRatesRankedByReimbursement,
  getBestPayingCode: claimFns.getBestPayingCode,
  createCptCodeEquivalency: claimFns.createCptCodeEquivalency,
  getCptCodeEquivalencies: claimFns.getCptCodeEquivalencies,
  getEquivalentCodesForIntervention: claimFns.getEquivalentCodesForIntervention,
  getAllCptCodeEquivalencies: claimFns.getAllCptCodeEquivalencies,
  deleteCptCodeEquivalency: claimFns.deleteCptCodeEquivalency,
  createAppeal: claimFns.createAppeal,
  getAppeals: claimFns.getAppeals,
  getAppealById: claimFns.getAppealById,
  getAppealsByClaimId: claimFns.getAppealsByClaimId,
  updateAppealRecord: claimFns.updateAppealRecord,
  getAppealsDashboard: claimFns.getAppealsDashboard,
  getUpcomingDeadlines: claimFns.getUpcomingDeadlines,
  getDeniedClaimsForAppeals: claimFns.getDeniedClaimsForAppeals,
  createClaimOutcome: claimFns.createClaimOutcome,
  getClaimOutcomes: claimFns.getClaimOutcomes,
  updateClaimOutcome: claimFns.updateClaimOutcome,
  getClaimOutcomeById: claimFns.getClaimOutcomeById,
  getClaimOutcomesForTraining: claimFns.getClaimOutcomesForTraining,

  // ==================== PAYMENTS ====================
  createPatientPaymentMethod: paymentFns.createPatientPaymentMethod,
  getPatientPaymentMethods: paymentFns.getPatientPaymentMethods,
  getPatientPaymentMethod: paymentFns.getPatientPaymentMethod,
  getDefaultPaymentMethod: paymentFns.getDefaultPaymentMethod,
  updatePatientPaymentMethod: paymentFns.updatePatientPaymentMethod,
  setDefaultPaymentMethod: paymentFns.setDefaultPaymentMethod,
  deletePatientPaymentMethod: paymentFns.deletePatientPaymentMethod,
  createPaymentTransaction: paymentFns.createPaymentTransaction,
  getPaymentTransactions: paymentFns.getPaymentTransactions,
  getPaymentTransaction: paymentFns.getPaymentTransaction,
  updatePaymentTransaction: paymentFns.updatePaymentTransaction,
  getPatientPaymentHistory: paymentFns.getPatientPaymentHistory,
  createPaymentPlan: paymentFns.createPaymentPlan,
  getPaymentPlans: paymentFns.getPaymentPlans,
  getPaymentPlan: paymentFns.getPaymentPlan,
  updatePaymentPlan: paymentFns.updatePaymentPlan,
  getPatientPaymentPlans: paymentFns.getPatientPaymentPlans,
  getActivePaymentPlans: paymentFns.getActivePaymentPlans,
  createPaymentPlanInstallment: paymentFns.createPaymentPlanInstallment,
  getPaymentPlanInstallments: paymentFns.getPaymentPlanInstallments,
  updatePaymentPlanInstallment: paymentFns.updatePaymentPlanInstallment,
  getDueInstallments: paymentFns.getDueInstallments,
  getPaymentPlanInstallment: paymentFns.getPaymentPlanInstallment,
  getUpcomingInstallments: paymentFns.getUpcomingInstallments,
  getOverdueInstallments: paymentFns.getOverdueInstallments,
  getPracticePaymentSettings: paymentFns.getPracticePaymentSettings,
  upsertPracticePaymentSettings: paymentFns.upsertPracticePaymentSettings,
  getPaymentStats: paymentFns.getPaymentStats,
  getPatientBalance: paymentFns.getPatientBalance,
  getPaymentPlanWithInstallments: paymentFns.getPaymentPlanWithInstallments,
  createPatientPayment: paymentFns.createPatientPayment,
  getPatientPayments: paymentFns.getPatientPayments,
  getPatientPaymentsByPractice: paymentFns.getPatientPaymentsByPractice,
  getWebhookEvent: paymentFns.getWebhookEvent,
  createWebhookEvent: paymentFns.createWebhookEvent,
  updateWebhookEventStatus: paymentFns.updateWebhookEventStatus,
  updatePatientPortalPaymentStatus: paymentFns.updatePatientPortalPaymentStatus,

  // ==================== CLINICAL ====================
  createSoapNote: clinicalFns.createSoapNote,
  getSoapNotes: clinicalFns.getSoapNotes,
  getSoapNote: clinicalFns.getSoapNote,
  getSoapNoteBySession: clinicalFns.getSoapNoteBySession,
  signSoapNote: clinicalFns.signSoapNote,
  updateSoapNoteCosignStatus: clinicalFns.updateSoapNoteCosignStatus,
  getPendingCosignNotes: clinicalFns.getPendingCosignNotes,
  getAllSoapNotes: clinicalFns.getAllSoapNotes,
  countAllSoapNotes: clinicalFns.countAllSoapNotes,
  createTreatmentPlan: clinicalFns.createTreatmentPlan,
  getTreatmentPlans: clinicalFns.getTreatmentPlans,
  getTreatmentPlan: clinicalFns.getTreatmentPlan,
  updateTreatmentPlan: clinicalFns.updateTreatmentPlan,
  getTreatmentPlanWithDetails: clinicalFns.getTreatmentPlanWithDetails,
  getPatientTreatmentPlans: clinicalFns.getPatientTreatmentPlans,
  getActiveTreatmentPlan: clinicalFns.getActiveTreatmentPlan,
  createTreatmentGoal: clinicalFns.createTreatmentGoal,
  getTreatmentGoals: clinicalFns.getTreatmentGoals,
  getTreatmentGoal: clinicalFns.getTreatmentGoal,
  updateTreatmentGoal: clinicalFns.updateTreatmentGoal,
  deleteTreatmentGoal: clinicalFns.deleteTreatmentGoal,
  createTreatmentObjective: clinicalFns.createTreatmentObjective,
  getTreatmentObjectives: clinicalFns.getTreatmentObjectives,
  getTreatmentObjective: clinicalFns.getTreatmentObjective,
  updateTreatmentObjective: clinicalFns.updateTreatmentObjective,
  deleteTreatmentObjective: clinicalFns.deleteTreatmentObjective,
  createTreatmentIntervention: clinicalFns.createTreatmentIntervention,
  getTreatmentInterventions: clinicalFns.getTreatmentInterventions,
  updateTreatmentIntervention: clinicalFns.updateTreatmentIntervention,
  deleteTreatmentIntervention: clinicalFns.deleteTreatmentIntervention,
  createGoalProgressNote: clinicalFns.createGoalProgressNote,
  getGoalProgressNotes: clinicalFns.getGoalProgressNotes,
  getSessionProgressNotes: clinicalFns.getSessionProgressNotes,
  createSoapNoteGoalProgress: clinicalFns.createSoapNoteGoalProgress,
  getSoapNoteGoalProgressBySoapNote: clinicalFns.getSoapNoteGoalProgressBySoapNote,
  getSoapNoteGoalProgressByGoal: clinicalFns.getSoapNoteGoalProgressByGoal,
  getSoapNoteGoalProgressByGoalWithDetails: clinicalFns.getSoapNoteGoalProgressByGoalWithDetails,
  getTreatmentPlanStats: clinicalFns.getTreatmentPlanStats,
  getPlansNeedingReview: clinicalFns.getPlansNeedingReview,
  createOutcomeMeasureTemplate: clinicalFns.createOutcomeMeasureTemplate,
  getOutcomeMeasureTemplates: clinicalFns.getOutcomeMeasureTemplates,
  getOutcomeMeasureTemplate: clinicalFns.getOutcomeMeasureTemplate,
  updateOutcomeMeasureTemplate: clinicalFns.updateOutcomeMeasureTemplate,
  getTemplatesByCategory: clinicalFns.getTemplatesByCategory,
  createPatientAssessment: clinicalFns.createPatientAssessment,
  getPatientAssessments: clinicalFns.getPatientAssessments,
  getPatientAssessment: clinicalFns.getPatientAssessment,
  getLatestPatientAssessment: clinicalFns.getLatestPatientAssessment,
  updatePatientAssessment: clinicalFns.updatePatientAssessment,
  getPracticeAssessments: clinicalFns.getPracticeAssessments,
  getPatientAssessmentHistory: clinicalFns.getPatientAssessmentHistory,
  createAssessmentSchedule: clinicalFns.createAssessmentSchedule,
  getPatientAssessmentSchedules: clinicalFns.getPatientAssessmentSchedules,
  getAssessmentSchedule: clinicalFns.getAssessmentSchedule,
  updateAssessmentSchedule: clinicalFns.updateAssessmentSchedule,
  deleteAssessmentSchedule: clinicalFns.deleteAssessmentSchedule,
  getDueAssessments: clinicalFns.getDueAssessments,
  getOutcomeMeasureStats: clinicalFns.getOutcomeMeasureStats,
  createReferralSource: clinicalFns.createReferralSource,
  getReferralSources: clinicalFns.getReferralSources,
  getReferralSource: clinicalFns.getReferralSource,
  updateReferralSource: clinicalFns.updateReferralSource,
  deleteReferralSource: clinicalFns.deleteReferralSource,
  createReferral: clinicalFns.createReferral,
  getReferrals: clinicalFns.getReferrals,
  getReferral: clinicalFns.getReferral,
  updateReferral: clinicalFns.updateReferral,
  updateReferralStatus: clinicalFns.updateReferralStatus,
  getPatientReferrals: clinicalFns.getPatientReferrals,
  getPendingReferrals: clinicalFns.getPendingReferrals,
  getReferralsNeedingFollowUp: clinicalFns.getReferralsNeedingFollowUp,
  createReferralCommunication: clinicalFns.createReferralCommunication,
  getReferralCommunications: clinicalFns.getReferralCommunications,
  getReferralStats: clinicalFns.getReferralStats,
  getReferralWithDetails: clinicalFns.getReferralWithDetails,
  getTherapyBank: clinicalFns.getTherapyBank,
  createTherapyBankEntry: clinicalFns.createTherapyBankEntry,
  deleteTherapyBankEntry: clinicalFns.deleteTherapyBankEntry,
  getExerciseBank: clinicalFns.getExerciseBank,
  createExerciseBankEntry: clinicalFns.createExerciseBankEntry,
  deleteExerciseBankEntry: clinicalFns.deleteExerciseBankEntry,

  // ==================== APPOINTMENTS ====================
  createAppointment: appointmentFns.createAppointment,
  getAppointments: appointmentFns.getAppointments,
  countAppointments: appointmentFns.countAppointments,
  getAppointmentsByDateRange: appointmentFns.getAppointmentsByDateRange,
  countAppointmentsByDateRange: appointmentFns.countAppointmentsByDateRange,
  getAppointment: appointmentFns.getAppointment,
  updateAppointment: appointmentFns.updateAppointment,
  cancelAppointment: appointmentFns.cancelAppointment,
  getAppointmentsForReminder: appointmentFns.getAppointmentsForReminder,
  getUpcomingAppointments: appointmentFns.getUpcomingAppointments,
  getUpcomingAppointmentsForReminders: appointmentFns.getUpcomingAppointmentsForReminders,
  markReminderSent: appointmentFns.markReminderSent,
  createRecurringAppointmentSeries: appointmentFns.createRecurringAppointmentSeries,
  getRecurringSeries: appointmentFns.getRecurringSeries,
  deleteRecurringSeries: appointmentFns.deleteRecurringSeries,
  updateRecurringSeries: appointmentFns.updateRecurringSeries,
  cancelRecurringSeries: appointmentFns.cancelRecurringSeries,
  getRecurrenceParent: appointmentFns.getRecurrenceParent,
  getAppointmentsBySeriesId: appointmentFns.getAppointmentsBySeriesId,
  updateSeriesBySeriesId: appointmentFns.updateSeriesBySeriesId,
  deleteSeriesBySeriesId: appointmentFns.deleteSeriesBySeriesId,
  cancelSeriesBySeriesId: appointmentFns.cancelSeriesBySeriesId,
  createWaitlistEntry: appointmentFns.createWaitlistEntry,
  getWaitlist: appointmentFns.getWaitlist,
  getWaitlistEntry: appointmentFns.getWaitlistEntry,
  updateWaitlistEntry: appointmentFns.updateWaitlistEntry,
  deleteWaitlistEntry: appointmentFns.deleteWaitlistEntry,
  getWaitlistForSlot: appointmentFns.getWaitlistForSlot,
  markWaitlistNotified: appointmentFns.markWaitlistNotified,
  markWaitlistScheduled: appointmentFns.markWaitlistScheduled,
  getWaitlistStats: appointmentFns.getWaitlistStats,
  expireOldWaitlistEntries: appointmentFns.expireOldWaitlistEntries,
  createReviewRequest: appointmentFns.createReviewRequest,
  getReviewRequests: appointmentFns.getReviewRequests,
  getReviewRequest: appointmentFns.getReviewRequest,
  updateReviewRequest: appointmentFns.updateReviewRequest,
  getReviewRequestStats: appointmentFns.getReviewRequestStats,
  getPatientsEligibleForReview: appointmentFns.getPatientsEligibleForReview,
  createGoogleReview: appointmentFns.createGoogleReview,
  getGoogleReviews: appointmentFns.getGoogleReviews,
  getGoogleReview: appointmentFns.getGoogleReview,
  updateGoogleReview: appointmentFns.updateGoogleReview,
  getReviewStats: appointmentFns.getReviewStats,
  createPatientFeedback: appointmentFns.createPatientFeedback,
  getPatientFeedback: appointmentFns.getPatientFeedback,
  getPatientFeedbackById: appointmentFns.getPatientFeedbackById,
  getPatientFeedbackByReviewRequest: appointmentFns.getPatientFeedbackByReviewRequest,
  updatePatientFeedback: appointmentFns.updatePatientFeedback,
  getPatientFeedbackStats: appointmentFns.getPatientFeedbackStats,
  getReviewRequestByToken: appointmentFns.getReviewRequestByToken,
  createAppointmentType: appointmentFns.createAppointmentType,
  getAppointmentTypes: appointmentFns.getAppointmentTypes,
  getAppointmentType: appointmentFns.getAppointmentType,
  updateAppointmentType: appointmentFns.updateAppointmentType,
  deleteAppointmentType: appointmentFns.deleteAppointmentType,
  setTherapistAvailability: appointmentFns.setTherapistAvailability,
  getTherapistAvailability: appointmentFns.getTherapistAvailability,
  getPracticeAvailability: appointmentFns.getPracticeAvailability,
  deleteTherapistAvailability: appointmentFns.deleteTherapistAvailability,
  addTherapistTimeOff: appointmentFns.addTherapistTimeOff,
  getTherapistTimeOff: appointmentFns.getTherapistTimeOff,
  deleteTherapistTimeOff: appointmentFns.deleteTherapistTimeOff,
  getBookingSettings: appointmentFns.getBookingSettings,
  getBookingSettingsBySlug: appointmentFns.getBookingSettingsBySlug,
  upsertBookingSettings: appointmentFns.upsertBookingSettings,
  createOnlineBooking: appointmentFns.createOnlineBooking,
  getOnlineBookings: appointmentFns.getOnlineBookings,
  getOnlineBooking: appointmentFns.getOnlineBooking,
  getOnlineBookingByCode: appointmentFns.getOnlineBookingByCode,
  updateOnlineBooking: appointmentFns.updateOnlineBooking,
  confirmOnlineBooking: appointmentFns.confirmOnlineBooking,
  cancelOnlineBooking: appointmentFns.cancelOnlineBooking,
  getAvailableSlots: appointmentFns.getAvailableSlots,
  createTelehealthSession: appointmentFns.createTelehealthSession,
  getTelehealthSessions: appointmentFns.getTelehealthSessions,
  getTelehealthSession: appointmentFns.getTelehealthSession,
  getTelehealthSessionByRoom: appointmentFns.getTelehealthSessionByRoom,
  getTelehealthSessionByAppointment: appointmentFns.getTelehealthSessionByAppointment,
  getTelehealthSessionByAccessCode: appointmentFns.getTelehealthSessionByAccessCode,
  updateTelehealthSession: appointmentFns.updateTelehealthSession,
  startTelehealthSession: appointmentFns.startTelehealthSession,
  endTelehealthSession: appointmentFns.endTelehealthSession,
  getUpcomingTelehealthSessions: appointmentFns.getUpcomingTelehealthSessions,
  getTodaysTelehealthSessions: appointmentFns.getTodaysTelehealthSessions,
  getTelehealthSettings: appointmentFns.getTelehealthSettings,
  upsertTelehealthSettings: appointmentFns.upsertTelehealthSettings,
  generateTelehealthRoomName: appointmentFns.generateTelehealthRoomName,
  generatePatientAccessCode: appointmentFns.generatePatientAccessCode,
  getCancellationStats: appointmentFns.getCancellationStats,
  getCancellationsByPatient: appointmentFns.getCancellationsByPatient,
  getCancellationTrend: appointmentFns.getCancellationTrend,
  createEligibilityAlert: appointmentFns.createEligibilityAlert,
  getEligibilityAlerts: appointmentFns.getEligibilityAlerts,
  getEligibilityAlert: appointmentFns.getEligibilityAlert,
  updateEligibilityAlert: appointmentFns.updateEligibilityAlert,
  acknowledgeEligibilityAlert: appointmentFns.acknowledgeEligibilityAlert,
  resolveEligibilityAlert: appointmentFns.resolveEligibilityAlert,
  dismissEligibilityAlert: appointmentFns.dismissEligibilityAlert,
  getOpenAlertsForAppointment: appointmentFns.getOpenAlertsForAppointment,
  getEligibilityAlertStats: appointmentFns.getEligibilityAlertStats,
  getAppointmentsNeedingEligibilityCheck: appointmentFns.getAppointmentsNeedingEligibilityCheck,
  createEligibilityAlertsBatch: appointmentFns.createEligibilityAlertsBatch,
  createAppointmentRequest: appointmentFns.createAppointmentRequest,
  getAppointmentRequest: appointmentFns.getAppointmentRequest,
  getPatientAppointmentRequests: appointmentFns.getPatientAppointmentRequests,
  getPracticeAppointmentRequests: appointmentFns.getPracticeAppointmentRequests,
  updateAppointmentRequest: appointmentFns.updateAppointmentRequest,
  getPendingAppointmentRequestsCount: appointmentFns.getPendingAppointmentRequestsCount,

  // ==================== INSURANCE ====================
  createEligibilityCheck: insuranceFns.createEligibilityCheck,
  getPatientEligibility: insuranceFns.getPatientEligibility,
  getEligibilityHistory: insuranceFns.getEligibilityHistory,
  createPatientInsuranceAuth: insuranceFns.createPatientInsuranceAuth,
  getPatientInsuranceAuth: insuranceFns.getPatientInsuranceAuth,
  getInsuranceAuthByToken: insuranceFns.getInsuranceAuthByToken,
  updateInsuranceAuth: insuranceFns.updateInsuranceAuth,
  getPatientAuthorizations: insuranceFns.getPatientAuthorizations,
  updateAuthorizationStatus: insuranceFns.updateAuthorizationStatus,
  getAuthorizationByToken: insuranceFns.getAuthorizationByToken,
  getAuthorizationById: insuranceFns.getAuthorizationById,
  createInsuranceAuthorization: insuranceFns.createInsuranceAuthorization,
  incrementAuthorizationResendCount: insuranceFns.incrementAuthorizationResendCount,
  incrementAuthorizationLinkAttempts: insuranceFns.incrementAuthorizationLinkAttempts,
  cacheInsuranceData: insuranceFns.cacheInsuranceData,
  getCachedInsuranceData: insuranceFns.getCachedInsuranceData,
  getPatientsWithStaleEligibility: insuranceFns.getPatientsWithStaleEligibility,
  markCacheAsStale: insuranceFns.markCacheAsStale,

  // ==================== ANALYTICS ====================
  getDashboardStats: analyticsFns.getDashboardStats,
  getRevenueByMonth: analyticsFns.getRevenueByMonth,
  getClaimsByStatus: analyticsFns.getClaimsByStatus,
  getTopDenialReasons: analyticsFns.getTopDenialReasons,
  getCollectionRate: analyticsFns.getCollectionRate,
  getCleanClaimsRate: analyticsFns.getCleanClaimsRate,
  getCapacityUtilization: analyticsFns.getCapacityUtilization,
  getDaysInAR: analyticsFns.getDaysInAR,
  getRevenueForecast: analyticsFns.getRevenueForecast,
  getTopReferringProviders: analyticsFns.getTopReferringProviders,
  getRevenueByLocationAndTherapist: analyticsFns.getRevenueByLocationAndTherapist,
  getWaitTimes: analyticsFns.getWaitTimes,

  // ==================== AUDIT / COMPLIANCE / PORTAL / MESSAGING ====================
  createAuditLog: auditFns.createAuditLog,
  createAuditLogEntry: auditFns.createAuditLogEntry,
  verifyAuditLogIntegrity: auditFns.verifyAuditLogIntegrity,
  getAuditLogsForResource: auditFns.getAuditLogsForResource,
  getAuditLogs: auditFns.getAuditLogs,
  getAuditLogsPaginated: auditFns.getAuditLogsPaginated,
  createBaaRecord: auditFns.createBaaRecord,
  getBaaRecords: auditFns.getBaaRecords,
  updateBaaRecord: auditFns.updateBaaRecord,
  deleteBaaRecord: auditFns.deleteBaaRecord,
  getExpiringBaaRecords: auditFns.getExpiringBaaRecords,
  createBreachIncident: auditFns.createBreachIncident,
  getBreachIncident: auditFns.getBreachIncident,
  updateBreachIncident: auditFns.updateBreachIncident,
  getBreachIncidentsByPractice: auditFns.getBreachIncidentsByPractice,
  getBreachesRequiringNotification: auditFns.getBreachesRequiringNotification,
  createAmendmentRequest: auditFns.createAmendmentRequest,
  getAmendmentRequest: auditFns.getAmendmentRequest,
  updateAmendmentRequest: auditFns.updateAmendmentRequest,
  getAmendmentRequestsByPatient: auditFns.getAmendmentRequestsByPatient,
  getPendingAmendmentRequests: auditFns.getPendingAmendmentRequests,
  getComplianceChecks: auditFns.getComplianceChecks,
  upsertComplianceCheck: auditFns.upsertComplianceCheck,
  generatePatientAccessToken: auditFns.generatePatientAccessToken,
  createConversation: auditFns.createConversation,
  getConversation: auditFns.getConversation,
  getConversationByToken: auditFns.getConversationByToken,
  getConversations: auditFns.getConversations,
  getPatientConversations: auditFns.getPatientConversations,
  updateConversation: auditFns.updateConversation,
  archiveConversation: auditFns.archiveConversation,
  createMessage: auditFns.createMessage,
  getMessage: auditFns.getMessage,
  getMessages: auditFns.getMessages,
  markMessageRead: auditFns.markMessageRead,
  markConversationReadByTherapist: auditFns.markConversationReadByTherapist,
  markConversationReadByPatient: auditFns.markConversationReadByPatient,
  softDeleteMessage: auditFns.softDeleteMessage,
  getUnreadCount: auditFns.getUnreadCount,
  getPatientUnreadCount: auditFns.getPatientUnreadCount,
  createMessageNotification: auditFns.createMessageNotification,
  updateMessageNotification: auditFns.updateMessageNotification,
  getPendingNotifications: auditFns.getPendingNotifications,
  refreshPatientAccessToken: auditFns.refreshPatientAccessToken,
  getConversationWithMessages: auditFns.getConversationWithMessages,
  generatePortalToken: auditFns.generatePortalToken,
  generateMagicLinkToken: auditFns.generateMagicLinkToken,
  createPatientPortalAccess: auditFns.createPatientPortalAccess,
  updatePatientPortalMagicLink: auditFns.updatePatientPortalMagicLink,
  getPatientPortalAccess: auditFns.getPatientPortalAccess,
  getPatientPortalByToken: auditFns.getPatientPortalByToken,
  getPatientPortalByMagicLink: auditFns.getPatientPortalByMagicLink,
  createMagicLink: auditFns.createMagicLink,
  useMagicLink: auditFns.useMagicLink,
  updatePortalAccess: auditFns.updatePortalAccess,
  refreshPortalToken: auditFns.refreshPortalToken,
  createPatientDocument: auditFns.createPatientDocument,
  getPatientDocuments: auditFns.getPatientDocuments,
  getPatientDocument: auditFns.getPatientDocument,
  updatePatientDocument: auditFns.updatePatientDocument,
  markDocumentViewed: auditFns.markDocumentViewed,
  markDocumentDownloaded: auditFns.markDocumentDownloaded,
  signDocument: auditFns.signDocument,
  getPatientPortalDashboard: auditFns.getPatientPortalDashboard,
};

export type Storage = typeof storage;
